version: '3.8'

services:
  sarah:
    build: .
    container_name: sarah-voice-assistant
    ports:
      - "5000:5000"
    volumes:
      # Persist memory and chat history
      - ./sarah_memory.json:/app/sarah_memory.json
      - ./chat_history.json:/app/chat_history.json
      # Mount .env file
      - ./.env:/app/.env:ro
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: unless-stopped
